// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvN2TJwVy_X-mhs4rGe7ybzmlD8-K4he8',
    appId: '1:1089061134907:web:44d3191dde758cf2ed721e',
    messagingSenderId: '1089061134907',
    projectId: 'learning-flutter-basics',
    authDomain: 'learning-flutter-basics.firebaseapp.com',
    storageBucket: 'learning-flutter-basics.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApQLJYfYmSLg5fgOk5v5M9i3zyKN4TTW4',
    appId: '1:1089061134907:android:7fad008c63df5b9bed721e',
    messagingSenderId: '1089061134907',
    projectId: 'learning-flutter-basics',
    storageBucket: 'learning-flutter-basics.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaE94bvkxGb9aWu7qENIpoout9zIwZF1c',
    appId: '1:1089061134907:ios:770fd14f596962d5ed721e',
    messagingSenderId: '1089061134907',
    projectId: 'learning-flutter-basics',
    storageBucket: 'learning-flutter-basics.appspot.com',
    iosBundleId: 'com.example.flutterBasics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaE94bvkxGb9aWu7qENIpoout9zIwZF1c',
    appId: '1:1089061134907:ios:a3b0d9ac5d41e96eed721e',
    messagingSenderId: '1089061134907',
    projectId: 'learning-flutter-basics',
    storageBucket: 'learning-flutter-basics.appspot.com',
    iosBundleId: 'com.example.flutterBasics.RunnerTests',
  );
}
